import { ADHKAR, DAILY_VERSES } from "@/lib/faith/content";
// English renderings explain the meaning; they are not Arabic recitation text.
const verses = [
  ["Ar-Ra'd","Believers find peace in remembering Allah. Truly, hearts find peace in His remembrance.","Remembering Allah and reflecting on His Book bring calm to believers' hearts and ease their anxiety.","Peace of heart"],
  ["Ash-Sharh","With hardship comes ease.","Ease accompanies difficulty. This is reassurance to remain hopeful and trust in Allah.","A door to hope"],
  ["Al-Baqarah","Remember Me and I will remember you. Give thanks to Me and do not be ungrateful.","Remember Allah and thank Him in your heart, words, and actions. He promises to remember those who remember Him.","Remembrance and gratitude"],
  ["Hud","Be patient: Allah does not let the reward of those who do good go to waste.","Remain steadfast in obedience and avoid wrongdoing. Allah preserves the reward of good deeds and patience.","Patience and goodness"],
  ["Ad-Duha","Your Lord will give to you, and you will be satisfied.","This is a promise to the Prophet of Allah's generosity and blessings, including what awaits him in the Hereafter.","Generosity and mercy"],
  ["Ash-Sharh","Indeed, with hardship comes ease.","The assurance of ease with hardship is repeated, encouraging steadfastness and hope in difficult times.","Renewed hope"],
];
const dhikr = [
  ["Surah Al-Ikhlas","Say: He is Allah, the One. Allah, the One on whom all depend. He neither begets nor was begotten, and none is equal to Him."],
  ["Surah Al-Falaq","Say: I seek refuge with the Lord of daybreak, from the evil of what He created, from the evil of darkness as it falls, from the evil of those who blow on knots, and from the evil of an envier when they envy."],
  ["Surah An-Nas","Say: I seek refuge with the Lord of mankind, the King of mankind, the God of mankind, from the evil of the retreating whisperer who whispers into people's hearts, from among jinn and mankind."],
  ["The foremost prayer for forgiveness","O Allah, You are my Lord; none deserves worship but You. You created me and I am Your servant. I keep Your covenant and promise as best I can. I seek refuge in You from the evil I have done. I acknowledge Your blessings upon me and my sins. Forgive me: no one forgives sins but You."],
  ["In the name of Allah","In the name of Allah, with whose name nothing on earth or in the heavens can cause harm. He is the All-Hearing, the All-Knowing."],
  ["Glorification and praise","Glory be to Allah, and praise belongs to Him."],
];
export const englishFromArabic: Record<string,string> = {
  "تعذّر حفظ اختيارك على هذا الجهاز. اسمح للتطبيق بحفظ البيانات وحاول مجددًا.":"Could not save your choice on this device. Allow the app to store data and retry.",
  "سجّل الدخول لحفظ اختيارك.":"Sign in to save your choice.","تحقّق من إعدادات الموقع.":"Check your location settings.","تعذّر حفظ تقدّم الذكر.":"Could not save your dhikr progress.",
  "تم نسخ الآية مع مرجعها.":"Verse and reference copied.","تعذّرت المشاركة. يمكنك تحديد النص ونسخه.":"Sharing failed. You can select and copy the text.","معًا على خير":"Together in goodness","لحظة إيمان":"A moment of faith","فسحة صغيرة للذكر والسكينة":"A little space for remembrance and peace",
  "آية اليوم":"Today's verse","سورة":"Surah","المعنى باختصار":"Meaning at a glance","بتصرّف من تفسير السعدي · اقرأ الأصل":"Editorial summary based on Al-Sa'di · Read the source","اقرأ في المصحف":"Read in the Quran","جارٍ المشاركة…":"Sharing…","مشاركة الآية":"Share verse",
  "ذكرٌ يرافق يومك":"Remembrance for your day","فتح أذكار الصباح":"Open morning adhkar","فتح أذكار المساء":"Open evening adhkar","أذكار الصباح":"Morning adhkar","أذكار المساء":"Evening adhkar","اكتملت اليوم":"Completed today","تقدّمك محفوظ لك على هذا الجهاز":"Your progress is saved on this device",
  "الصلاة القادمة":"Next prayer","إعداد مواقيت الصلاة":"Prayer time settings","صلاتك، في وقتها":"Your prayer, on time","اختر مدينتك لعرض الصلاة القادمة ومواقيت يومك.":"Choose your city to see the next prayer and today's times.","اختيار المدينة":"Choose city","غدًا":"Tomorrow","موعدك القادم":"Coming up","جارٍ تحميل المواقيت…":"Loading prayer times…","بعض المواقيت غير متاحة لهذا الموقع. راجع إعدادات الحساب.":"Some times are unavailable for this location. Check your calculation settings.","المواقيت غير متاحة الآن.":"Prayer times are unavailable right now.",
  "سجّل الدخول لعرض مواقيت الصلاة.":"Sign in to see prayer times.","تعذّر تحميل المواقيت. تحقّق من الاتصال أو إعدادات الموقع.":"Could not load prayer times. Check your connection and location settings.","تعذّر تحميل المواقيت. حاول مجددًا.":"Could not load prayer times. Please retry.","الشروق":"Sunrise","تعذّر التحديث؛ تُعرض مواقيت اليوم المحفوظة.":"Refresh failed. Today's verified saved times are shown.","المصدر: AlAdhan":"Source: AlAdhan","تحديث مواقيت الصلاة":"Refresh prayer times","تحميل…":"Loading…","تحديث":"Refresh","المواقيت حسب الإعدادات المختارة؛ طابقها مع تقويم مسجدك.":"Times use your chosen settings. Check them against your mosque's timetable.",
  "تحديد الموقع غير متاح. اختر مدينة من القائمة.":"Location is unavailable. Choose a city from the list.","تعذّر معرفة المنطقة الزمنية. اختر مدينة من القائمة.":"Could not find your timezone. Choose a city from the list.","موقعي الحالي":"My current location","لم نتمكّن من تحديد الموقع. اسمح به أو اختر مدينة من القائمة.":"Could not get your location. Allow access or choose a city.","اختر مدينتك أو استخدم تحديد الموقع أولًا.":"Choose your city or use your location first.",
  "حسب موقعك":"For your location","مواقيت الصلاة":"Prayer times","إعداداتك مستقلة على هذا الجهاز. اختر المدينة التي تصلي فيها.":"These settings are private to your device. Choose the city where you pray.","المدينة":"City","اختر مدينة":"Choose a city","جارٍ تحديد الموقع…":"Finding your location…","استخدم موقعي الحالي":"Use my current location","لمدينة أخرى، استخدم موقعك. يُستخدم لحساب المواقيت ولا يُشارك مع الحساب الآخر.":"For another city, use your location. It is used for calculations and not shared with your partner.",
  "طريقة حساب المواقيت":"Calculation method","إعدادات حساب إضافية":"More calculation settings","حساب وقت العصر":"Asr calculation","الجمهور":"Standard","الحنفي":"Hanafi","تقدير الفجر والعشاء في خطوط العرض العالية":"Fajr and Isha at high latitudes","بحسب زاوية الشفق":"Twilight angle","منتصف الليل":"Middle of the night","سُبع الليل":"One seventh of the night","مفيد لشمال السويد. اختر الطريقة المعتمدة في مسجدك.":"Useful in northern Sweden. Choose your mosque's method.","حفظ المواقيت":"Save prayer settings","إلغاء":"Cancel","إزالة الموقع المحفوظ":"Remove saved location",
  "ذكر وسكينة":"Remembrance and peace","اكتمل":"Completed","من":"of","أذكار":"adhkar","حجم الخط العادي":"Regular text","خط أكبر":"Larger text","تقدّم الأذكار":"Adhkar progress","اختيار الذكر":"Choose dhikr","بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ":"In the name of Allah, the Most Merciful, the Especially Merciful.","النص في المصحف":"Original Quran text","التراجع عن مرة":"Undo one count","اكتمل هذا الذكر":"This dhikr is complete","تسجيل قراءة الذكر":"Record this recitation","تم الذكر":"Completed","قرأت الذكر":"I recited it"," · قراءة واحدة":" · once"," · مرات":" · repetitions","إعادة عداد هذا الذكر":"Reset this counter","تقبّل الله منك. أتممت الأذكار المختارة لهذه الفترة.":"May Allah accept it. You completed the selected adhkar for this period.","كل نقرة تحفظ تقدّمك على هذا الجهاز.":"Each tap saves your progress on this device.","السابق":"Previous","الذكر التالي":"Next dhikr","العودة للرئيسية":"Back to Home",
  "الفجر":"Fajr","الظهر":"Dhuhr","العصر":"Asr","المغرب":"Maghrib","العشاء":"Isha","رابطة العالم الإسلامي":"Muslim World League","أمريكا الشمالية — ISNA":"North America — ISNA","أم القرى — مكة":"Umm Al-Qura — Makkah","الهيئة المصرية للمساحة":"Egyptian General Authority of Survey","اتحاد المنظمات الإسلامية في فرنسا":"Union of Islamic Organisations in France",
  "أوميو — Umeå، السويد":"Umeå, Sweden","ستوكهولم، السويد":"Stockholm, Sweden","غوتنبرغ، السويد":"Gothenburg, Sweden","مالمو، السويد":"Malmö, Sweden","دمشق، سوريا":"Damascus, Syria","حلب، سوريا":"Aleppo, Syria",
  "أبو داود 5082 · حسن، الألباني":"Abu Dawud 5082 · Hasan, Al-Albani","صحيح البخاري 6306":"Sahih Al-Bukhari 6306","أبو داود 5088 · صحيح، الألباني":"Abu Dawud 5088 · Sahih, Al-Albani","صحيح مسلم 2692":"Sahih Muslim 2692",
  "كيف أفعّل الميكروفون والكاميرا؟":"How do I allow microphone and camera access?",
  "على الآيفون: افتح رابط التطبيق نفسه في Safari، ومن قائمة الصفحة افتح إعدادات الموقع واجعل الميكروفون والكاميرا «سماح» أو «سؤال». راجع أيضًا إعدادات الجهاز ← التطبيقات ← Safari. بعدها أغلق التطبيق وافتحه وجرّب مجددًا، دون حذف بياناته.":"On iPhone, open this app's URL in Safari. Open the page menu and Website Settings, then set microphone and camera to Allow or Ask. Also check Settings → Apps → Safari. Reopen the installed app and retry without clearing its data.",
  "على أندرويد: افتح أذونات الموقع في Chrome وتأكد من السماح بالميكروفون والكاميرا. إذا كان الرابط مفتوحًا داخل تطبيق آخر، افتحه مباشرة في Safari أو Chrome.":"On Android, allow microphone and camera in Chrome's site permissions. If this link is open inside another app, open it directly in Safari or Chrome.",
  "التطبيق لا يستطيع تجاوز إذن محظور من إعدادات الجهاز. للفيديو يمكنك الرد بالصوت فقط.":"The app cannot override a permission blocked in device settings. You can answer a video call with audio only.",
};
DAILY_VERSES.forEach((v,i)=>{const en=verses[i];Object.assign(englishFromArabic,{[v.surah]:en[0],[v.text]:en[1],[v.meaning]:en[2],[v.theme]:en[3]});});
ADHKAR.forEach((v,i)=>Object.assign(englishFromArabic,{[v.title]:dhikr[i][0],[v.text]:dhikr[i][1]}));
