"use client";
import { useLanguage } from "@/components/i18n/LanguageProvider";

import {Overlay} from "@/components/common/Overlay";
import {SpecialDatesSection} from "@/components/story/SpecialDatesSection";
import {CalendarHeart,CalendarDays,Plus,Trash2,X} from "lucide-react";
import {useState} from "react";
import {PageHeading} from "@/components/common/PageHeading";
import {ConfirmDialog} from "@/components/common/ConfirmDialog";
import {useTogether} from "@/components/providers/TogetherProvider";
import {errorMessage} from "@/lib/errors";
import type {ImportantDate} from "@/lib/types";
export default function MomentsPage(){
  const { t: uiText, locale } = useLanguage();

 const {profile,dates,addDate,deleteDate}=useTogether();
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[title,setTitle]=useState(""),[date,setDate]=useState(""),[notes,setNotes]=useState(""),[kind,setKind]=useState<ImportantDate['kind']>("date"),[error,setError]=useState(""),[tab,setTab]=useState<"upcoming"|"past">("upcoming"),[deleting,setDeleting]=useState<ImportantDate|null>(null);
 const now=Date.now(),upcoming=[...dates].filter(d=>!d.specialType&&+new Date(d.date)>=now).sort((a,b)=>+new Date(a.date)-+new Date(b.date)),past=[...dates].filter(d=>!d.specialType&&+new Date(d.date)<now).sort((a,b)=>+new Date(a.date)-+new Date(b.date));
 const next=upcoming[0],shown=tab==="upcoming"?upcoming:past;
 async function save(){if(busy)return;if(!title.trim()||!date){setError("Give your moment a name and a date.");return;}setBusy(true);setError("");try{await addDate({title:title.trim(),date:new Date(date).toISOString(),kind,notes:notes.trim()||undefined});setTitle("");setDate("");setNotes("");setKind("date");setOpen(false);}catch(error:unknown){setError(errorMessage(error));}finally{setBusy(false);}}
 return <div className="moments-experience"><PageHeading eyebrow={uiText("MAKE TIME FOR EACH OTHER")} title={uiText("More to look forward to.")} description={uiText("Your dates, milestones, and next adventures.")} action={<button className="soft-btn compact-action" aria-label={uiText("Add a date")} onClick={()=>{setError("");setOpen(true);}}><Plus size={18}/><span>{uiText("Add a date")}</span></button>}/>
  <SpecialDatesSection key={profile.myUserId}/>
  {next&&<section className="moment-hero"><span className="eyebrow">{uiText("YOUR NEXT MOMENT")}</span><div><h2 dir="auto">{next.title}</h2><span className="moment-countdown"><b>{Math.max(0,Math.ceil((+new Date(next.date)-now)/86400000))}</b><small>{uiText("days to go")}</small></span></div><p><CalendarDays size={17}/>{new Date(next.date).toLocaleString(locale,{weekday:"long",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</p></section>}
  <div className="experience-segments moment-filters"><button aria-pressed={tab==="upcoming"} className={tab==="upcoming"?"active":""} onClick={()=>setTab("upcoming")}>{uiText("Upcoming ")}<span>{upcoming.length}</span></button><button aria-pressed={tab==="past"} className={tab==="past"?"active":""} onClick={()=>setTab("past")}>{uiText("Our history ")}<span>{past.length}</span></button></div>
  <div className="moment-list">{shown.map(d=><article className="moment-row" key={d.id}><div className="moment-date-stamp"><small>{new Date(d.date).toLocaleDateString(locale,{month:"short"})}</small><b>{new Date(d.date).getDate()}</b></div><div className="moment-copy"><span className="kind-label">{uiText({date:"Date / plan",milestone:"Milestone",trip:"Trip",anniversary:"Anniversary"}[d.kind])}</span><h3 dir="auto">{d.title}</h3><time>{new Date(d.date).toLocaleString(locale,{weekday:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}</time>{d.notes&&<p dir="auto">{d.notes}</p>}</div><button className="icon-button" aria-label={uiText("Delete {0}", [d.title])} onClick={()=>setDeleting(d)}><Trash2 size={18}/></button></article>)}</div>
  {!shown.length&&<div className="experience-empty"><span className="empty-icon"><CalendarHeart size={30}/></span><h2>{tab==="upcoming"?uiText("Make a little time for us."):uiText("Your story is still unfolding.")}</h2><p>{tab==="upcoming"?uiText("Plan a call, a dinner, or your next day together."):uiText("Your past moments will stay here.")}</p><button className="soft-btn" onClick={()=>setOpen(true)}>{uiText("Add a special date")}</button></div>}
  {open&&<Overlay><section className="modal"><button className="dialog-close" disabled={busy} aria-label={uiText("Close")} onClick={()=>setOpen(false)}><X size={20}/></button><span className="eyebrow">{uiText("SOMETHING FOR YOU TWO")}</span><h2>{uiText("Plan a moment")}</h2>{error&&<p className="notice error" role="alert">{uiText(error)}</p>}<form className="form-stack" onSubmit={e=>{e.preventDefault();void save();}}><label className="field-label" htmlFor="moment-title">{uiText("What are you planning?")}</label><input id="moment-title" className="input" placeholder={uiText("Dinner, a trip, a video call…")} value={title} maxLength={160} onChange={e=>setTitle(e.target.value)} required/><label className="field-label" htmlFor="moment-date">{uiText("Date and time")}</label><input id="moment-date" className="input" type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} required/><label className="field-label" htmlFor="moment-kind">{uiText("Type")}</label><select id="moment-kind" className="input" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="date">{uiText("Date / plan")}</option><option value="milestone">{uiText("Milestone")}</option><option value="trip">{uiText("Trip")}</option><option value="anniversary">{uiText("Anniversary")}</option></select><label className="field-label" htmlFor="moment-notes">{uiText("Notes (optional)")}</label><textarea id="moment-notes" className="input" rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/><div className="modal-actions"><button type="button" className="soft-btn secondary" disabled={busy} onClick={()=>setOpen(false)}>{uiText("Cancel")}</button><button className="soft-btn" disabled={busy}>{busy?uiText("Saving…"):uiText("Save date")}</button></div></form></section></Overlay>}
  {deleting&&<ConfirmDialog title={uiText("Delete this date?")} description={uiText("“{0}” will be removed from your shared moments.", [deleting.title])} onClose={()=>setDeleting(null)} onConfirm={()=>deleteDate(deleting.id)}/>}
 </div>;
}
