const test=require('node:test'),assert=require('node:assert/strict');
const {load}=require('./load-ts.cjs');
const {datePayload,cleanupDatePhoto,saveImportantDate}=load('lib/together/datePhotos.ts',{}, {'@/lib/together/media':{prepareProfilePhoto:async f=>f,mediaExtension:()=> 'png'}});
const input={title:'Engagement',date:'2024-01-01T12:00:00Z',kind:'milestone',specialType:'engagement',localDate:'2024-01-01',repeatsYearly:true,photoPath:''};
const owner={userId:'me',coupleId:'pair'},file={name:'photo.png',type:'image/png',size:10};
function fixture(opts={}){
 const state={uploads:[],removed:[],writes:[],reads:0,sessions:0,row:null};
 const client={auth:{getSession:async()=>({data:{session:{user:{id:++state.sessions>1&&opts.switch?'other':'me'}}}})},storage:{from:()=>({upload:async(path)=>{state.uploads.push(path);return {error:null};},remove:async(paths)=>{state.removed.push(...paths);return {error:null};}})},from:()=>{
  let write=null,filters={};const q={insert:x=>{write=x;return q;},update:x=>{write=x;return q;},eq:(k,v)=>{filters[k]=v;return q;},select:()=>q,limit:async()=>({data:opts.referenced?[{id:'another'}]:[],error:opts.readError?'offline':null}),single:async()=>{state.writes.push(write);state.row=opts.failed?null:{...write,id:'stable',couple_id:'pair'};return {data:opts.ackError?null:state.row,error:opts.ackError?'lost ACK':null};},maybeSingle:async()=>{state.reads++;return {data:state.row,error:opts.readError?'offline':null};}};return q;
 }};return {client,state};
}
test('date payload maps only supported fields, keeps original day, and explicitly clears a photo',()=>{const p=datePayload({...input,unexpected:'not persisted'});assert.equal(p.photo_path,null);assert.equal(p.local_date,'2024-01-01');assert.equal(p.repeats_yearly,true);assert.ok(!('unexpected' in p));assert.ok(!('photo_path' in datePayload({...input,photoPath:undefined})));});
test('date upload creates a pair-private path and saves the stable row ID',async()=>{const {client,state}=fixture();const row=await saveImportantDate(client,owner,'stable',input,false,file);assert.match(state.uploads[0],/^pair\/me\/dates\/stable-.+\.png$/);assert.equal(row.photo_path,state.uploads[0]);assert.equal(state.writes[0].id,'stable');assert.equal(state.removed.length,0);});
test('choosing album media does not upload or remove the original album object',async()=>{const {client,state}=fixture();const photoPath='pair/partner/memories/photo.jpg';const row=await saveImportantDate(client,owner,'stable',{...input,photoPath},true);assert.equal(row.photo_path,photoPath);assert.equal(state.uploads.length,0);await cleanupDatePhoto(client,photoPath,'pair');assert.equal(state.removed.length,0);});
test('lost acknowledgement recovers a committed row without deleting its photo',async()=>{const {client,state}=fixture({ackError:true});const row=await saveImportantDate(client,owner,'stable',input,false,file);assert.equal(row.id,'stable');assert.equal(state.reads,1);assert.equal(state.removed.length,0);});
test('confirmed failed writes clean only the new unreferenced dedicated photo',async()=>{const {client,state}=fixture({ackError:true,failed:true});await assert.rejects(saveImportantDate(client,owner,'stable',input,false,file));assert.deepEqual(state.removed,state.uploads);});
test('unknown outcomes and referenced dedicated photos never trigger media deletion',async()=>{for(const opts of [{readError:true},{referenced:true}]){const {client,state}=fixture({...opts,ackError:true,failed:true});await assert.rejects(saveImportantDate(client,owner,'stable',input,false,file));assert.equal(state.removed.length,0);}});
test('account change after upload prevents date mutation and cleans only an unreferenced upload',async()=>{const {client,state}=fixture({switch:true});await assert.rejects(saveImportantDate(client,owner,'stable',input,false,file),/account changed/);assert.equal(state.writes.length,0);assert.deepEqual(state.removed,state.uploads);});
test('invalid image selection fails before storage writes',async()=>{for(const f of [{...file,size:0},{...file,size:16*1024*1024},{...file,type:'video/mp4'}]){const {client,state}=fixture();await assert.rejects(saveImportantDate(client,owner,'stable',input,false,f),/15 MB/);assert.equal(state.uploads.length,0);}});
test('cleanup rejects other-pair, traversal, album and story paths',async()=>{const {client,state}=fixture();for(const path of ['other/me/dates/x.jpg','pair/me/dates/../x.jpg','pair/me/memories/x.jpg','pair/me/story/x.jpg'])await cleanupDatePhoto(client,path,'pair');assert.equal(state.removed.length,0);});
