const test=require('node:test'),assert=require('node:assert/strict');const {load}=require('./load-ts.cjs');
const owner={myUserId:'a',coupleId:'pair',paired:true};const settings={mode:'selected',memoryIds:['m1','m1'],paths:[]};const file={name:'cover.jpg',type:'image/jpeg',size:100};
function fixture(options={}){
 const calls={uploads:[],removed:[],updates:[],pairs:[]};let saved={id:'pair',story_cover_mode:'fixed',story_cover_memory_ids:[],story_cover_paths:[]};
 const supabase={auth:{getSession:async()=>({data:{session:{user:{id:options.user||'a'}}}})},storage:{from:()=>({upload:async(path,file)=>{calls.uploads.push(path);return {error:options.failUpload===calls.uploads.length?new Error('Upload failed'):null};},remove:async(paths)=>{calls.removed.push(...paths);return {error:null};}})},from:()=>{let input;const q={update:values=>{input=values;calls.updates.push(values);return q;},eq:(key,value)=>{calls.pairs.push([key,value]);return q;},select:()=>q,single:async()=>{if(!options.failUpdate||options.committed)saved={...saved,...input};return {data:options.failUpdate?null:saved,error:options.failUpdate?{message:'Update failed'}:null};},maybeSingle:async()=>({data:options.recoveryFails?null:saved,error:options.recoveryFails?{message:'Offline'}:null})};return q;}};
 let n=0;const api=load('lib/together/storyCovers.ts',{}, {'@/lib/supabase/client':{getSupabaseBrowser:()=>supabase},'@/lib/together/media':{mediaExtension:()=> 'jpg',prepareProfilePhoto:async f=>f,storagePath:()=>`pair/a/story/${++n}.jpg`}});return {api,calls};
}
test('cover saves deduplicate selected memory IDs, upload each dedicated image and update only the owned pair',async()=>{const {api,calls}=fixture();const row=await api.saveStoryCovers(owner,settings,[file,file]);assert.deepEqual(Array.from(row.story_cover_memory_ids),['m1']);assert.equal(row.story_cover_paths.length,2);assert.deepEqual(calls.pairs,[['id','pair']]);assert.equal(calls.removed.length,0);});
test('changing account before cover save blocks all uploads and writes',async()=>{const {api,calls}=fixture({user:'b'});await assert.rejects(api.saveStoryCovers(owner,settings,[file]),/account changed/);assert.equal(calls.uploads.length,0);assert.equal(calls.updates.length,0);});
test('invalid cover file sizes and too many selections fail before uploading',async()=>{const {api,calls}=fixture();for(const files of [[{...file,size:0}],[{...file,type:'video/mp4'}],[{...file,size:11*1024*1024}],Array(21).fill(file)])await assert.rejects(api.saveStoryCovers(owner,settings,files));assert.equal(calls.uploads.length,0);});
test('upload failure cleans up new uncommitted uploads, never previous album or cover paths',async()=>{const {api,calls}=fixture({failUpload:2});await assert.rejects(api.saveStoryCovers(owner,settings,[file,file]),/Upload failed/);assert.deepEqual(calls.removed,['pair/a/story/1.jpg']);assert.equal(calls.updates.length,0);});
test('ambiguous update failure recovers a committed cover and preserves its uploaded media',async()=>{const {api,calls}=fixture({failUpdate:true,committed:true});const row=await api.saveStoryCovers(owner,settings,[file]);assert.equal(row.story_cover_paths[0],'pair/a/story/1.jpg');assert.equal(calls.removed.length,0);});
test('confirmed failed save removes only newly uploaded unreferenced files',async()=>{const {api,calls}=fixture({failUpdate:true});await assert.rejects(api.saveStoryCovers(owner,settings,[file]),/Update failed/);assert.deepEqual(calls.removed,['pair/a/story/1.jpg']);});
test('unverifiable update outcome never deletes possibly committed uploads',async()=>{const {api,calls}=fixture({failUpdate:true,recoveryFails:true});await assert.rejects(api.saveStoryCovers(owner,settings,[file]));assert.equal(calls.removed.length,0);});
