"use client";
import { useLanguage } from "@/components/i18n/LanguageProvider";

import { useEffect, useRef, useState } from "react";
import { Check, ImagePlus, X } from "lucide-react";
import { AppDialog } from "@/components/common/Overlay";
import { useTogether } from "@/components/providers/TogetherProvider";
import { signMediaPath } from "@/lib/together/media";
import { errorMessage } from "@/lib/errors";
import type { StoryCoverMode } from "@/lib/story";
function UploadedCover({path,remove}:{path:string;remove:()=>void}){
  const { t: uiText } = useLanguage();
const [url,setUrl]=useState("");useEffect(()=>{let live=true;void signMediaPath(path).then(src=>{if(live)setUrl(src||"");});return()=>{live=false;};},[path]);return <button className="story-cover-choice" onClick={remove} aria-label={uiText("Remove uploaded cover from rotation")} aria-pressed="true">{url&&<img src={url} alt={uiText("Uploaded story cover")} loading="lazy"/>}<b><X size={14}/></b><span>{uiText("Remove from rotation")}</span></button>;}
function PendingCover({file,remove}:{file:File;remove:()=>void}){
  const { t: uiText } = useLanguage();
const [url,setUrl]=useState("");useEffect(()=>{const url=URL.createObjectURL(file);setUrl(url);return()=>URL.revokeObjectURL(url);},[file]);return <button className="story-cover-choice" onClick={remove} aria-label={uiText("Remove {0}", [file.name])}><img src={url} loading="lazy" alt={file.name}/><b><X size={14}/></b><span>{file.name}</span></button>;}
export default function StoryCoverDialog({onClose}:{onClose:()=>void}){
  const { t: uiText } = useLanguage();

  const {profile,memories,saveStoryCoverSettings,hasOlderMemories,loadingOlderMemories,loadOlderMemories}=useTogether();
  const [mode,setMode]=useState<StoryCoverMode>(profile.storyCoverMode|| (profile.storyPhotoPath?"fixed":"memories")),[ids,setIds]=useState(profile.storyCoverMemoryIds||[]),[paths,setPaths]=useState(profile.storyCoverPaths||[]),[files,setFiles]=useState<File[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState("");
  const input=useRef<HTMLInputElement>(null),saving=useRef(false);
  function choose(id:string){if(busy)return;setError("");setIds(prev=>prev.includes(id)?prev.filter(x=>x!==id):prev.length<60?[...prev,id]:prev);}
  function append(newFiles:File[]){if(paths.length+files.length+newFiles.length>20){setError("Choose up to 20 uploaded cover photos.");return;}if(newFiles.some(f=>!f.type.startsWith("image/")||!f.size||f.size>10*1024*1024)){setError("Choose photos smaller than 10 MB each.");return;}setFiles(prev=>[...prev,...newFiles]);setError("");}
  async function save(){if(saving.current)return;if(mode==="selected"&&!ids.length&&!paths.length&&!files.length){setError("Select at least one album photo or upload a cover.");return;}saving.current=true;setBusy(true);setError("");try{await saveStoryCoverSettings({mode,memoryIds:ids,paths},files);onClose();}catch(error){setError(errorMessage(error));}finally{saving.current=false;setBusy(false);}}
  return <AppDialog title={uiText("Your story, a new photo each day")} eyebrow={uiText("OUR STORY COVER")} busy={busy} onClose={onClose} footer={<><button className="soft-btn secondary" disabled={busy} onClick={onClose}>{uiText("Cancel")}</button><button className="soft-btn" disabled={busy||!profile.storyCoverMode} onClick={()=>void save()}>{busy?uiText("Saving covers…"):uiText("Save cover settings")}</button></>}>
    {!profile.storyCoverMode&&<p className="notice error" role="alert">{uiText("Apply database update 014 to enable daily covers.")}</p>}{error&&<p className="notice error" role="alert">{uiText(error)}</p>}<fieldset className="story-mode-options" disabled={busy}><legend className="field-label">{uiText("Choose what appears on Our Story")}</legend>{([['memories','Daily photo from Memories','Automatically rotates through all album photos, including earlier memories.'],['selected','Photos we choose','Pick album photos or upload dedicated covers. One appears each day.'],['fixed','Keep our current cover','Keep your existing shared cover without daily rotation.']] as const).map(([id,title,detail])=><label key={id}><input type="radio" name="cover-mode" value={id} checked={mode===id} onChange={()=>setMode(id)}/><span><strong>{uiText(title)}</strong><small>{uiText(detail)}</small></span></label>)}</fieldset>
    <p className="hint">{uiText("The choice is shared between both accounts. The daily photo changes at 00:00 UTC so you both see the same cover. Videos are never used as covers.")}</p>
    {mode==="fixed"&&<>{profile.storyPhotoUrl?<img className="story-cover-current" src={profile.storyPhotoUrl} alt={uiText("Current story cover")}/>:<p className="hint">{uiText("No fixed cover yet. Choose “Photos we choose” and select one photo to keep the same cover each day.")}</p>}</>}
    {mode==="selected"&&<><h3>{uiText("Choose from Memories")}</h3><label className="field-label" htmlFor="cover-search">{uiText("Find a photo")}</label><input id="cover-search" className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder={uiText("Search captions")} disabled={busy}/><p className="hint">{ids.length}{uiText(" selected · Up to 60 album photos")}</p><div className="story-cover-grid">{memories.filter(m=>m.kind!=="video"&&m.caption.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).map(m=><button className="story-cover-choice" key={m.id} aria-label={uiText("Use {0} as cover", [m.caption])} aria-pressed={ids.includes(m.id)} disabled={busy} onClick={()=>choose(m.id)}><img src={m.src} loading="lazy" alt={m.caption}/>{ids.includes(m.id)&&<b><Check size={14}/></b>}<span dir="auto">{m.caption}</span></button>)}</div>{!memories.some(m=>m.kind!=="video")&&<p className="hint">{uiText("Your album has no photos yet. You can upload dedicated covers below.")}</p>}{hasOlderMemories&&<button className="soft-btn secondary" disabled={busy||loadingOlderMemories} onClick={()=>void loadOlderMemories().catch(e=>setError(errorMessage(e)))}>{loadingOlderMemories?uiText("Loading…"):uiText("Load earlier memories")}</button>}<div className="story-cover-configured"><h3>{uiText("Dedicated cover photos")}</h3><p className="hint">{uiText("These are private covers, not new album entries. Removing an album photo here does not delete it from Memories.")}</p><div className="story-cover-grid">{paths.map(path=><UploadedCover key={path} path={path} remove={()=>{if(!busy)setPaths(prev=>prev.filter(p=>p!==path));}}/>)}{files.map((file,i)=><PendingCover key={`${file.name}-${i}`} file={file} remove={()=>{if(!busy)setFiles(prev=>prev.filter((_,j)=>j!==i));}}/>)}</div><button className="soft-btn secondary story-cover-upload" disabled={busy||paths.length+files.length>=20} onClick={()=>input.current?.click()}><ImagePlus size={18}/>{uiText("Upload cover photos")}</button><input ref={input} hidden type="file" multiple accept="image/*" onChange={e=>{append(Array.from(e.target.files||[]));e.target.value="";}}/></div></>}
  </AppDialog>;
}
